### PR TITLE
Implement the `/scanner/updateStatus` post action

### PR DESCRIPTION
**Pull request by jamesshank**
Hello and thanks for putting the cycles into the `tenablesc-client` repo! We're excited to start using it, but we have the need for a few more endpoints. Hopefully the stuff that we need can help others! 
 
Per the docs [here](https://docs.tenable.com/tenablesc/api/Scanner.htm#ScannerRESTReference-/scanner/updateStatus), this PR implements the `/scanner/updateStatus` post action.

I'm happy to support any feedback.

### CODE REVIEW

**Comment by palantirtech** [comment]
Thanks for your interest in [palantir/tenablesc-client](https://github.com/palantir/tenablesc-client), @jamesshank! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

**Comment by jamesshank** [comment]
Working with Datadog to get approval for the CLA.

**Comment by dreamlibrarian** [comment]
👍 
https://docs.tenable.com/tenablesc/api/Scanner.htm#scanner_updateStatus_POST Looks good to me, thanks for the addition!

Will merge once CLA is g2g, holler if you have questions. (_sigh_ changelog-bot doesn't comprehend forks. that's... somewhat less than helpful)

If you drop 
```
type: feature
feature:
  description: Implement the /scanner/updateStatus post action
  links:
  - https://github.com/palantir/tenablesc-client/pull/10
``` 
in a file `changelog)/@unreleased/pr-10.v2.yml` it'll replicate the changelog experience with none of the convenience; I can also just shim that in later. I'll ask around regarding sane ways to handle fork-changelogs, as I may have a misconfig here.

update: no misconfig, changelog bot's just very simple and doesn't know how to cope with forks. All good. :/

**Comment by jamesshank** [comment]
@dreamlibrarian We should be good to go!

**Comment by dreamlibrarian** [comment]
Huzzah, thank you and many happy returns.

**Pull request merged**
